name: Portfolio Static Website CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Check HTML syntax (Optional)
      run: |
        sudo apt-get update
        sudo apt-get install tidy -y
        tidy -e index.html || true  # Lint HTML, will not fail the build

    - name: Archive Website Files
      run: |
        mkdir ../artifact
        cp -r * ../artifact

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-web
        path: ../artifact
